/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'bg-primary': '#F7F8FA',
        'bg-surface': '#FFFFFF',
        'bg-dark': '#0D1F35',
        'bg-dark-2': '#162840',
        'accent-gold': '#E8A94D',
        'accent-gold-light': '#FEF3DC',
        'text-primary': '#0D1F35',
        'text-secondary': '#5A7184',
        'text-muted': '#9BAFBF',
        'text-white': '#F7F8FA',
        border: '#E4EAF0',
        'border-dark': '#1E3A52',
        success: '#27AE7A',
        'success-bg': '#E8F8F2',
        warning: '#E8A94D',
        'warning-bg': '#FEF3DC',
        error: '#E85D4A',
        'error-bg': '#FEECE9',
        info: '#3B82F6',
        'info-bg': '#EFF6FF',
        'coming-soon-bg': '#F0F4F8',
        'coming-soon-text': '#9BAFBF',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        arabic: ['"Tajawal"', 'sans-serif'],
      },
      fontSize: {
        xs: '12px',
        sm: '13px',
        base: '14px',
        md: '15px',
        lg: '18px',
        xl: '22px',
        '2xl': '28px',
        '3xl': '36px',
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '20px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
        lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
        gold: '0 4px 14px 0 rgba(232, 169, 77, 0.39)',
      },
    },
  },
  plugins: [],
};
